In [1]:
import numpy as np 
from zomba.multiObjective.simulators import moSLBSimulator

In [2]:
K = 20
d = 8 
m = 3

env = moSLBSimulator(K, d, m)
env.reset(verbose=1)

# objective: 3, 
# dimension: 8,
# arms: 20,
# optimal arms: [ 3  6  7  9 14 18],
Regret for each arm: [0.11811305870849839, 0.12660770665177762, 0.09165296523904241, 0, 0.04467538378468286, 0.16813916476354712, 0, 0, 0.21940249103026044, 0, 0.3008684647861774, 0.09003978416669346, 0.06633717862090557, 0.28685901295215366, 0, 0.16202845878460975, 0.18127976056706938, 0.22380192248555916, 0, 0.12127215469545555],
Expected rewards for each arm: 
[[-0.25300009  0.13722074  0.0576477 ]
 [ 0.09453289 -0.30690271 -0.27807475]
 [-0.01998469  0.18494364  0.08185712]
 [-0.10151659  0.07123026  0.41901528]
 [ 0.2156409  -0.3896666  -0.11730655]
 [-0.20394537 -0.09429887  0.07941947]
 [-0.11239182  0.2553338   0.28064623]
 [ 0.17638628  0.34639685  0.17351009]
 [-0.4788705  -0.11119571  0.06124374]
 [-0.0358062   0.08887206  0.30671953]
 [-0.12448219  0.03100181 -0.1899823 ]
 [ 0.10420968 -0.0621006  -0.42285912]
 [ 0.03589203  0.04443152  0.10717291]
 [-0.26863361  0.05953783 -0.22183602]
 [ 0.2

In [3]:
K = 100
d = 8 
m = 4
priority = [[0,1], [2,3]]
env = moSLBSimulator(K, d, m, obj_preference='MPL-PC', priority=priority)
env.reset(verbose=1, seed=1234)

# objective: 4, 
# dimension: 8,
# arms: 100,
# optimal arms: [24 62 67],
Regret for each arm: [array([0.2, 0.1]), array([0.1, 0. ]), array([0.4, 0. ]), array([0.3, 0. ]), array([0.1, 0. ]), array([0.1, 0. ]), array([0.5, 0. ]), array([0.3, 0.1]), array([0.2, 0.3]), array([0.1, 0. ]), array([0.2, 0.1]), array([0.1, 0. ]), array([0.1, 0.2]), array([0.4, 0.1]), array([0. , 0.1]), array([0.1, 0. ]), array([0.3, 0.1]), array([0.2, 0.1]), array([0.1, 0. ]), array([0.6, 0. ]), array([0.3, 0. ]), array([0.4, 0.2]), array([0.2, 0. ]), array([0. , 0.3]), array([0., 0.]), array([0.1, 0.1]), array([0.1, 0. ]), array([0.4, 0. ]), array([0.7, 0. ]), array([0.6, 0. ]), array([0.4, 0. ]), array([0.6, 0. ]), array([0.2, 0. ]), array([0.2, 0. ]), array([0.1, 0. ]), array([0.4, 0. ]), array([0.2, 0. ]), array([0.2, 0.2]), array([0. , 0.1]), array([0.1, 0.4]), array([0.2, 0.2]), array([0.1, 0. ]), array([0.3, 0.1]), array([0.2, 0. ]), array([0.2, 0. ]), array([0. , 0.4]), array([0.5, 0. ]), array([0.3, 0

In [4]:
K = 10
d = 8 
m = 3
priority = [[0,1], [2]]
env = moSLBSimulator(K, d, m, obj_preference='MPL-PC', priority=priority)
env.reset(verbose=1)

# objective: 3, 
# dimension: 8,
# arms: 10,
# optimal arms: [1 5],
Regret for each arm: [array([0.2, 0.1]), array([0., 0.]), array([0.8, 0.3]), array([0.6, 0.3]), array([0.2, 0. ]), array([0., 0.]), array([0.4, 0.2]), array([0.3, 0.2]), array([0.3, 0.9]), array([0.4, 0. ])],
Expected rewards for each arm: 
[[ 0.3  0.1  0.1]
 [ 0.5  0.2  0.7]
 [-0.3 -0.1 -0.2]
 [-0.1 -0.1 -0.5]
 [ 0.3  0.5  0.3]
 [ 0.6  0.2  0.7]
 [ 0.1  0.   0.1]
 [ 0.2 -0.   0.1]
 [ 0.2 -0.7  0. ]
 [ 0.1  0.5  0.2]]
Arms' context: [[ 0.06021271  0.06366356 -0.36430342  0.35473476  0.4068174   0.12848355
  -0.38924798 -0.0865461 ]
 [-0.45706634  0.53004161 -0.49451189 -0.01821896  0.10674301 -0.12869763
  -0.33500047  0.16767983]
 [ 0.03744751 -0.04249387 -0.12713445  0.3356808  -0.40654862  0.42602994
   0.16702522  0.06067131]
 [ 0.42942824 -0.3051127  -0.03383216 -0.18759978  0.30106552  0.36055944
  -0.62658071  0.09370688]
 [-0.0337798   0.24312003  0.02946615  0.55358392  0.10598951 -0.271518
  -0.5408769  -0.27

In [8]:
K = 10
d = 8 
m = 4
priority = [[0,1], [2,3]]
env = moSLBSimulator(K, d, m, obj_preference='MPL-Pl', priority=priority)
env.reset(verbose=1)

# objective: 4, 
# dimension: 8,
# arms: 10,
# optimal arms: [array([1, 3, 7, 9]), array([1, 3, 7, 9])],
Regret for each arm: [array([0.32715029, 0.        ]), array([0., 0.]), array([0.10543975, 0.        ]), array([0., 0.]), array([0.37073275, 0.        ]), array([0.11829705, 0.        ]), array([0.04212882, 0.        ]), array([0., 0.]), array([0.4251587, 0.       ]), array([0., 0.])],
Expected rewards for each arm: 
[[-0.26758596  0.1674521  -0.48513986 -0.30105467]
 [ 0.21577036  0.3079263  -0.36536171  0.51193754]
 [-0.04587541  0.40695515 -0.60550057  0.31158278]
 [ 0.30325828 -0.23947346 -0.15753564  0.1095114 ]
 [-0.36746695  0.26038657 -0.13877613 -0.10723528]
 [-0.05873271  0.49573162  0.14665674 -0.1840085 ]
 [ 0.17364154  0.05344701 -0.31984004  0.00673017]
 [ 0.19087146  0.39267059  0.24754731 -0.06799478]
 [-0.36559436  0.18709162 -0.61277129  0.20955356]
 [ 0.05956434  0.63111932 -0.17018304  0.27630586]]
Arms' context: [[ 0.24829285 -0.2739454  -0.20817674 -0.19853088 